version: "3.8"

services:
    laravel-vue-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-vue-app
        volumes:
            - .:/var/www
        ports:
            - "8000:9000"
